[package]
name = "kolorz"
version = "1.0.0"
edition = "2024"
description = "A silly little library for printing kolored text to the terminal "
repository = "https://github.com/dotzenith/kolorz.rs"
license = "MIT"

[dependencies]
rand = "0.8.5"
